version = 1
SPDX-PackageName = "carbonio-ws-collaboration-ui"
SPDX-PackageSupplier = "Zextras <https://www.zextras.com>"

[[annotations]]
path = [".idea/**", ".vscode/**", ".husky/**", ".nvmrc", "package.json", "pnpm-lock.yaml", ".npmrc", "tsconfig.json", "CHANGELOG.md",
".github/**", "THIRDPARTIES", "README.md", ".gitignore", ".prettierrc.js", "src/chats/assets/**", "src/meetings/assets/**", "Dockerfile",
"shared/package.json", "shared/tsconfig.json", "shared/src/network/API_VERSIONING.md","pnpm-workspace.yaml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "CC0-1.0"
