/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { WsEvent, WsEventType } from '../../types/network/websocket/wsEvents';

const legacyEventMap: Record<string, string> = {
	websocketConnected: WsEventType.INITIALIZATION,
	pong: WsEventType.PONG,

	ROOM_CREATED: WsEventType.ROOM_CREATED,
	ROOM_UPDATED: WsEventType.ROOM_UPDATED,
	ROOM_DELETED: WsEventType.ROOM_DELETED,
	ROOM_OWNER_PROMOTED: WsEventType.ROOM_OWNER_PROMOTED,
	ROOM_OWNER_DEMOTED: WsEventType.ROOM_OWNER_DEMOTED,
	ROOM_PICTURE_CHANGED: WsEventType.ROOM_PICTURE_CHANGED,
	ROOM_PICTURE_DELETED: WsEventType.ROOM_PICTURE_DELETED,
	ROOM_MEMBER_ADDED: WsEventType.ROOM_MEMBER_ADDED,
	ROOM_MEMBER_REMOVED: WsEventType.ROOM_MEMBER_REMOVED,
	ROOM_MUTED: WsEventType.ROOM_MUTED,
	ROOM_UNMUTED: WsEventType.ROOM_UNMUTED,
	ROOM_HISTORY_CLEARED: WsEventType.ROOM_HISTORY_CLEARED,

	MEETING_CREATED: WsEventType.MEETING_CREATED,
	MEETING_STARTED: WsEventType.MEETING_STARTED,
	MEETING_PARTICIPANT_JOINED: WsEventType.MEETING_PARTICIPANT_JOINED,
	MEETING_PARTICIPANT_LEFT: WsEventType.MEETING_PARTICIPANT_LEFT,
	MEETING_STOPPED: WsEventType.MEETING_STOPPED,
	MEETING_DELETED: WsEventType.MEETING_DELETED,
	MEETING_AUDIO_STREAM_CHANGED: WsEventType.MEETING_AUDIO_STREAM_CHANGED,
	MEETING_MEDIA_STREAM_CHANGED: WsEventType.MEETING_MEDIA_STREAM_CHANGED,
	MEETING_AUDIO_ANSWERED: WsEventType.MEETING_AUDIO_ANSWERED,
	MEETING_SDP_OFFERED: WsEventType.MEETING_SDP_OFFERED,
	MEETING_SDP_ANSWERED: WsEventType.MEETING_SDP_ANSWERED,
	MEETING_PARTICIPANT_SUBSCRIBED: WsEventType.MEETING_PARTICIPANT_SUBSCRIBED,
	MEETING_PARTICIPANT_TALKING: WsEventType.MEETING_PARTICIPANT_TALKING,
	MEETING_PARTICIPANT_CLASHED: WsEventType.MEETING_PARTICIPANT_CLASHED,
	MEETING_WAITING_PARTICIPANT_JOINED: WsEventType.MEETING_WAITING_PARTICIPANT_JOINED,
	MEETING_WAITING_PARTICIPANT_ACCEPTED: WsEventType.MEETING_WAITING_PARTICIPANT_ACCEPTED,
	MEETING_WAITING_PARTICIPANT_REJECTED: WsEventType.MEETING_WAITING_PARTICIPANT_REJECTED,
	MEETING_WAITING_PARTICIPANT_CLASHED: WsEventType.MEETING_WAITING_PARTICIPANT_CLASHED,
	MEETING_RECORDING_STARTED: WsEventType.MEETING_RECORDING_STARTED,
	MEETING_RECORDING_STOPPED: WsEventType.MEETING_RECORDING_STOPPED,
	MEETING_PARTICIPANT_HAND_RAISED: WsEventType.MEETING_PARTICIPANT_HAND_RAISED,
	MEETING_PARTICIPANT_HAND_RAISED_LIST: WsEventType.MEETING_PARTICIPANT_HAND_RAISED_LIST
};

// DEPRECATED: This function exists for backward compatibility with previous versions.
//  * Remove once support for v1.6.1 is officially dropped.
export function normalizeEventType(event: Record<string, unknown>): WsEvent {
	return {
		...event,
		type: legacyEventMap[event.type as string] || event.type
	} as WsEvent;
}
