/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { WsEvent, WsEventType } from '../../types/network/websocket/wsEvents';

const legacyEventMap: Record<string, string> = {
	websocketConnected: WsEventType.INITIALIZATION,
	pong: WsEventType.PONG,

	ROOM_CREATED_LEGACY: WsEventType.ROOM_CREATED,
	ROOM_UPDATED_LEGACY: WsEventType.ROOM_UPDATED,
	ROOM_DELETED_LEGACY: WsEventType.ROOM_DELETED,
	OWNER_PROMOTED: WsEventType.ROOM_OWNER_PROMOTED,
	OWNER_DEMOTED: WsEventType.ROOM_OWNER_DEMOTED,
	ROOM_PIC_CHANGED: WsEventType.ROOM_PICTURE_CHANGED,
	ROOM_PIC_DELETED: WsEventType.ROOM_PICTURE_DELETED,
	MEMBER_ADDED: WsEventType.ROOM_MEMBER_ADDED,
	MEMBER_REMOVED: WsEventType.ROOM_MEMBER_REMOVED,
	ROOM_MUTED_LEGACY: WsEventType.ROOM_MUTED,
	ROOM_UNMUTED_LEGACY: WsEventType.ROOM_UNMUTED,
	HISTORY_CLEARED: WsEventType.ROOM_HISTORY_CLEARED,

	MEETING_CREATED_LEGACY: WsEventType.MEETING_CREATED,
	MEETING_STARTED_OLD: WsEventType.MEETING_STARTED,
	PARTICIPANT_JOINED: WsEventType.MEETING_JOINED,
	PARTICIPANT_LEFT: WsEventType.MEETING_LEFT,
	MEETING_ENDED: WsEventType.MEETING_STOPPED,
	MEETING_REMOVED: WsEventType.MEETING_DELETED,
	AUDIO_STREAM_CHANGED: WsEventType.MEETING_AUDIO_STREAM_CHANGED,
	MEDIA_STREAM_CHANGED: WsEventType.MEETING_MEDIA_STREAM_CHANGED,
	AUDIO_ANSWERED: WsEventType.MEETING_AUDIO_ANSWERED,
	SDP_OFFERED: WsEventType.MEETING_SDP_OFFERED,
	SDP_ANSWERED: WsEventType.MEETING_SDP_ANSWERED,
	PARTICIPANT_SUBSCRIBED: WsEventType.MEETING_PARTICIPANT_SUBSCRIBED,
	PARTICIPANT_TALKING: WsEventType.MEETING_PARTICIPANT_TALKING,
	PARTICIPANT_CLASHED: WsEventType.MEETING_PARTICIPANT_CLASHED,
	WAITING_PARTICIPANT_JOINED: WsEventType.MEETING_WAITING_PARTICIPANT_JOINED,
	USER_ACCEPTED: WsEventType.MEETING_USER_ACCEPTED,
	USER_REJECTED: WsEventType.MEETING_USER_REJECTED,
	WAITING_PARTICIPANT_CLASHED: WsEventType.MEETING_WAITING_PARTICIPANT_CLASHED,
	RECORDING_STARTED: WsEventType.MEETING_RECORDING_STARTED,
	RECORDING_STOPPED: WsEventType.MEETING_RECORDING_STOPPED,
	HAND_RAISED: WsEventType.MEETING_PARTICIPANT_HAND_RAISED,
	HAND_RAISED_LIST: WsEventType.MEETING_PARTICIPANT_HAND_RAISED_LIST
};

// DEPRECATED: This function exists for backward compatibility with version 1.6.0.
//  * Remove once support for v1.6.0 is officially dropped.
export function normalizeEventType(event: Record<string, unknown>): WsEvent {
	return {
		...event,
		type: legacyEventMap[event.type as string] || event.type
	} as WsEvent;
}
